# Generated by Django 6.0.5 on 2026-05-07 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente_periodo_dias'),
        ('inventario', '0002_cuentaporpagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_pagar', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='folio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='folio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='ingrediente',
            constraint=models.UniqueConstraint(fields=('cliente', 'nombre'), name='unique_ingrediente_per_cliente'),
        ),
    ]
