# Generated by Django 6.0.5 on 2026-05-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_compra_cliente_cuentaporpagar_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
