# Generated by Django 6.0.5 on 2026-05-12 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_cliente_required'),
        ('productos', '0003_cliente_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidad', models.CharField(choices=[('unidad', 'Unidad'), ('kilo', 'Kilogramo'), ('gramo', 'Gramo'), ('litro', 'Litro'), ('ml', 'Mililitro'), ('caja', 'Caja'), ('pieza', 'Pieza'), ('bolsa', 'Bolsa'), ('paquete', 'Paquete')], default='unidad', max_length=20)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='inventario.ingrediente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_ingredientes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'unique_together': {('producto', 'ingrediente')},
            },
        ),
    ]
