# Generated by Django 6.0.5 on 2026-05-19 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cliente_estado_cliente_cliente_estado_pago'),
        ('inventario', '0007_proveedor_compra_proveedor_fk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('merma', 'Merma'), ('devolucion', 'Devolucion')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['cliente', 'estado', 'fecha'], name='compra_cliente_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['ingrediente', 'cantidad_actual'], name='inv_ingrediente_cantidad'),
        ),
    ]
