# Generated by Django 6.0.5 on 2026-05-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_custom_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Restaurante', max_length=200)),
                ('rfc', models.CharField(blank=True, default='XAXX010101000', max_length=13)),
                ('direccion', models.TextField(blank=True, default='Calle Principal #123')),
                ('telefono', models.CharField(blank=True, default='+52 55 1234 5678', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('simbolo_moneda', models.CharField(default='C$', max_length=5)),
                ('tasa_impuesto', models.FloatField(default=0.16, help_text='Ej: 0.16 para 16%')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurante/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion del Restaurante',
                'verbose_name_plural': 'Configuracion del Restaurante',
            },
        ),
    ]
