# Generated by Django 6.0.5 on 2026-05-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configrestaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='configrestaurante',
            name='dias_credito_proveedor',
            field=models.PositiveIntegerField(default=30, help_text='Dias para pagar a proveedores (cuentas por pagar)'),
        ),
    ]
