# Generated by Django 6.0.5 on 2026-05-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configrestaurante_dias_credito_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visible_password',
            field=models.CharField(blank=True, default='', help_text='Contraseña visible solo para administradores', max_length=255),
        ),
    ]
