# Generated by Django 6.0.5 on 2026-05-07 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_visible_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=200)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('simbolo_moneda', models.CharField(default='C$', max_length=5)),
                ('admin_username', models.CharField(max_length=150, unique=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('admin_password_visible', models.CharField(max_length=255)),
                ('plan', models.CharField(choices=[('basico', 'Basico'), ('profesional', 'Profesional'), ('premium', 'Premium')], default='basico', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado'), ('prueba', 'Periodo de Prueba')], default='prueba', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago_proximo', models.DateTimeField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='configrestaurante',
            name='tasa_impuesto',
            field=models.FloatField(default=0.15, help_text='Ej: 0.15 para 15%'),
        ),
        migrations.AddField(
            model_name='configrestaurante',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='user',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.cliente'),
        ),
        migrations.CreateModel(
            name='PagoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
    ]
