# Generated by Django 6.0.5 on 2026-05-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente_alter_configrestaurante_tasa_impuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='periodo_dias',
            field=models.PositiveIntegerField(default=30, help_text='Dias del periodo contratado'),
        ),
    ]
