# Generated by Django 6.0.5 on 2026-05-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente_periodo_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='plan',
        ),
    ]
