# Generated by Django 6.0.5 on 2026-05-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_configrestaurante_cliente_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='configrestaurante',
            name='rfc',
            field=models.CharField(blank=True, default='XAXX010101000', max_length=13, verbose_name='RUC'),
        ),
    ]
