# Generated by Django 6.0.5 on 2026-05-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cliente_rfc_alter_configrestaurante_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='configrestaurante',
            name='porcentaje_servicio',
            field=models.FloatField(default=0.1, help_text='Ej: 0.10 para 10%'),
        ),
    ]
