# Generated by Django 6.0.5 on 2026-05-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_configrestaurante_porcentaje_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configrestaurante',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='core.cliente'),
        ),
    ]
