# Generated by Django 6.0.5 on 2026-05-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_configrestaurante_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configrestaurante',
            name='logo',
        ),
    ]
