# Generated by Django 6.0.5 on 2026-05-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_logo_field'),
    ]

    operations = [
    ]
