# Generated by Django 6.0.5 on 2026-05-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_can_manage_mesas_to_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado'), ('prueba', 'Periodo de Prueba')], db_index=True, default='prueba', max_length=20),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['estado', 'fecha_pago_proximo'], name='cliente_estado_pago'),
        ),
    ]
