# Generated by Django 6.0.5 on 2026-05-05 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comandas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('cliente_rfc', models.CharField(blank=True, max_length=13)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('propina', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sin_impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_con_impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='comandas.comanda')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
