# Generated by Django 6.0.5 on 2026-05-07 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0003_comanda_cliente_alter_comanda_codigo_and_more'),
        ('core', '0007_cliente_periodo_dias'),
        ('facturacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='folio',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.UniqueConstraint(fields=('cliente', 'folio'), name='unique_factura_folio_per_cliente'),
        ),
    ]
