# Generated by Django 6.0.5 on 2026-05-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_cliente_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente_rfc',
            field=models.CharField(blank=True, max_length=13, verbose_name='RUC del cliente'),
        ),
    ]
