# Generated by Django 6.0.5 on 2026-05-12 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_alter_factura_cliente_rfc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cambio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cambio a devolver al cliente', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='divisa_monto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Equivalente en otra moneda', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='divisa_nombre',
            field=models.CharField(blank=True, help_text='Ej: USD, EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='divisa_tasa',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa de cambio usada', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto recibido del cliente en efectivo', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CajaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('retiro', 'Retiro')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='facturacion.cajaapertura')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='facturacion.factura')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
