# Generated by Django 6.0.5 on 2026-05-14 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0004_cliente_required'),
        ('facturacion', '0006_factura_cambio_factura_divisa_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='items_json',
            field=models.TextField(blank=True, help_text='Items en formato JSON (para llevar)'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo',
            field=models.CharField(choices=[('mesa', 'Mesa'), ('llevar', 'Para llevar')], default='mesa', max_length=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='comanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='comandas.comanda'),
        ),
    ]
