# Generated by Django 6.0.5 on 2026-05-19 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0005_alter_comanda_estado_alter_comanda_fecha_creacion_and_more'),
        ('core', '0015_alter_cliente_estado_cliente_cliente_estado_pago'),
        ('facturacion', '0007_factura_items_json_factura_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajaapertura',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], db_index=True, default='abierta', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente', 'estado', 'fecha_emision'], name='factura_cliente_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente', 'metodo_pago', 'estado'], name='factura_cliente_metodo_estado'),
        ),
    ]
