# Generated by Django 6.0.5 on 2026-05-05 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pin', models.CharField(blank=True, max_length=6, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('comandas_atendidas', models.PositiveIntegerField(default=0)),
                ('propinas_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(limit_choices_to={'role__in': ['waiter', 'cashier']}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_mesero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mesero',
                'verbose_name_plural': 'Meseros',
            },
        ),
    ]
