# Generated by Django 6.0.5 on 2026-05-07 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente_periodo_dias'),
        ('meseros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesero',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meseros', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='mesero',
            name='codigo_pin',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
