# Generated by Django 6.0.5 on 2026-05-05 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comandas', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='mesero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comandaitem',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='comandas.comanda'),
        ),
        migrations.AddField(
            model_name='comandaitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
    ]
