# Generated by Django 6.0.5 on 2026-05-07 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0002_initial'),
        ('core', '0007_cliente_periodo_dias'),
        ('mesas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='comanda',
            constraint=models.UniqueConstraint(fields=('cliente', 'codigo'), name='unique_comanda_codigo_per_cliente'),
        ),
    ]
