# Generated by Django 6.0.5 on 2026-05-19 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0004_cliente_required'),
        ('core', '0015_alter_cliente_estado_cliente_cliente_estado_pago'),
        ('mesas', '0004_alter_mesa_estado_mesa_mesa_cliente_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('en_cocina', 'En Cocina'), ('en_preparacion', 'En Preparación'), ('lista', 'Lista para Servir'), ('sirviendo', 'Sirviendo'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], db_index=True, default='abierta', max_length=20),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='prioridad',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('vip', 'VIP')], db_index=True, default='normal', max_length=20),
        ),
        migrations.AddIndex(
            model_name='comanda',
            index=models.Index(fields=['estado', 'prioridad', 'fecha_creacion'], name='comanda_estado_prioridad_fecha'),
        ),
        migrations.AddIndex(
            model_name='comanda',
            index=models.Index(fields=['cliente', 'estado'], name='comanda_cliente_estado'),
        ),
        migrations.AddIndex(
            model_name='comanda',
            index=models.Index(fields=['cliente', 'fecha_creacion'], name='comanda_cliente_fecha'),
        ),
    ]
