# Generated by Django 6.0.5 on 2026-05-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('zona', models.CharField(choices=[('interior', 'Interior'), ('terraza', 'Terraza'), ('bar', 'Bar'), ('vip', 'VIP'), ('jardin', 'Jardín')], default='interior', max_length=20)),
                ('capacidad', models.PositiveIntegerField(help_text='Número de personas')),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('mantenimiento', 'Mantenimiento')], default='libre', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
            },
        ),
    ]
