# Generated by Django 6.0.5 on 2026-05-07 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente_periodo_dias'),
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='mesa',
            constraint=models.UniqueConstraint(fields=('cliente', 'numero'), name='unique_mesa_per_cliente'),
        ),
    ]
