# Generated by Django 6.0.5 on 2026-05-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cliente_estado_cliente_cliente_estado_pago'),
        ('mesas', '0003_cliente_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('mantenimiento', 'Mantenimiento')], db_index=True, default='libre', max_length=20),
        ),
        migrations.AddIndex(
            model_name='mesa',
            index=models.Index(fields=['cliente', 'estado'], name='mesa_cliente_estado'),
        ),
    ]
