# Generated by Django 6.0.5 on 2026-05-08 03:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id_backup', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(editable=False, max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='respaldos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tamaño_mb', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('restaurando', 'Restaurando'), ('restaurado', 'Restaurado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('fecha_restauracion', models.DateTimeField(blank=True, null=True)),
                ('hash_md5', models.CharField(blank=True, editable=False, help_text='Hash de integridad del respaldo', max_length=32)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldos_creados', to=settings.AUTH_USER_MODEL)),
                ('restaurado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldos_restaurados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respaldo de Base de Datos',
                'verbose_name_plural': 'Respaldos de Base de Datos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
